name: tp_listview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.4.0 <4.0.0'
  

dependencies:
  
  flutter:
    sdk: flutter
  
  table_calendar: ^3.1.2
  awesome_snackbar_content: ^0.1.3
  syncfusion_flutter_datepicker: ^26.2.5
  go_router: ^14.2.1
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/IconoLocker.jpg"
  
  
flutter: 
 uses-material-design: true
 assets: 
  - assets/images/Safe Safe.jpg

